version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/development/nginx/Dockerfile
    volumes:
      - ./:/var/www
      # ATTENTION : Assurez-vous que le fichier ./docker/development/nginx/nginx.conf existe et N'EST PAS un dossier !
      # Si ce n'est pas le cas, commentez la ligne ci-dessous ou adaptez le chemin :
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Alternative :
      # - ${NGINX_CONF_PATH:-./docker/development/nginx/nginx.conf}:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - laravel-production
    environment:
      APP_ENV: ${APP_ENV}
      APP_URL: ${APP_URL}
      APP_NAME: ${APP_NAME}
      APP_KEY: ${APP_KEY}
      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_LEVEL: ${LOG_LEVEL}
      VITE_APP_NAME: ${VITE_APP_NAME}

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    env_file:
      - .env.production
    user: "1000:1000"
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./public:/var/www/public
    networks:
      - laravel-production
    environment:
      APP_ENV: ${APP_ENV}
      APP_URL: ${APP_URL}
      APP_NAME: ${APP_NAME}
      APP_KEY: ${APP_KEY}
      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      BROADCAST_CONNECTION: ${BROADCAST_CONNECTION}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

networks:
  laravel-production:
