version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/development/nginx/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - laravel-development

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
    networks:
      - laravel-development
    depends_on:
      - postgres
      - rabbitmq
      - meilisearch
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

  workspace:
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - laravel-development
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

  postgres:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    networks:
      - laravel-development

  redis:
    image: redis:alpine
    networks:
      - laravel-development

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - laravel-development

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=masterKey
    ports:
      - "7700:7700"
    networks:
      - laravel-development

  websockets:
    image: quay.io/soketi/soketi:latest-16-alpine
    environment:
      - SOKETI_DEBUG=1
      - SOKETI_METRICS_ENABLED=1
      - SOKETI_DEFAULT_APP_ID=app-id
      - SOKETI_DEFAULT_KEY=app-key
      - SOKETI_DEFAULT_SECRET=app-secret
    ports:
      - "6001:6001"
    networks:
      - laravel-development

depends_on:
  - php-fpm
  - workspace
  - postgres
  - redis
  - rabbitmq
  - meilisearch
  - websockets

networks:
  laravel-development:

volumes:
  postgres-data-development:
