services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: whatspro-app
        restart: unless-stopped
        volumes:
            # Pour le développement, décommente la ligne suivante :
            # - ./:/var/www/html:rw
            - logs_data:/var/www/html/storage/logs
        environment:
            - APP_NAME=${APP_NAME:-WhatsPro}
            - APP_ENV=${APP_ENV:-production}
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=${APP_DEBUG:-"false"}
            - APP_URL=${APP_URL:-http://whatspro-api.local}

            - DB_CONNECTION=${DB_CONNECTION:-pgsql}
            - DB_HOST=${DB_HOST:-host.docker.internal}
            - DB_PORT=${DB_PORT:-5432}
            - DB_DATABASE=${DB_DATABASE:-whatspro_api}
            - DB_USERNAME=${DB_USERNAME:-postgres}
            - DB_PASSWORD=${DB_PASSWORD:-}

            - QUEUE_CONNECTION=${QUEUE_CONNECTION:-redis}
            - SESSION_DRIVER=${SESSION_DRIVER:-database}
            - CACHE_STORE=${CACHE_STORE:-database}
            - REDIS_CLIENT=${REDIS_CLIENT:-phpredis}
            - REDIS_HOST=${REDIS_HOST:-88.223.92.13}
            - REDIS_PORT=${REDIS_PORT:-5448}
            - REDIS_USERNAME=${REDIS_USERNAME:-default}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_DB=${REDIS_DB:-0}

            - BROADCAST_CONNECTION=${BROADCAST_CONNECTION:-pusher}
            - PUSHER_APP_ID=${PUSHER_APP_ID:-oL6RX1pQdlKTPqAr}
            - PUSHER_APP_KEY=${PUSHER_APP_KEY:-bSM7rJucBDeIplGF}
            - PUSHER_APP_SECRET=${PUSHER_APP_SECRET:-xPxXWx0Lwx4QWy7eEGUyaQXpf790QGP0*}
            - PUSHER_HOST=${PUSHER_HOST:-localhost}
            - PUSHER_PORT=${PUSHER_PORT:-6001}
            - PUSHER_SCHEME=${PUSHER_SCHEME:-http}
            - PUSHER_USE_TLS=${PUSHER_USE_TLS:-"0"}
            - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER:-mt1}

            - MAIL_MAILER=${MAIL_MAILER:-smtp}
            - MAIL_HOST=${MAIL_HOST:-mailpit.applix.fr}
            - MAIL_PORT=${MAIL_PORT:-1025}
            - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-"noreply@whatspro.com"}
            - MAIL_FROM_NAME=${MAIL_FROM_NAME:-WhatsPro}

            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-0C15b0npFBL3fE3LDsWS}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-LDo1yDtOZN9wSM34fT2hJsZqwjV5HIWZMTFEdvM2}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
            - AWS_BUCKET=${AWS_BUCKET:-whatspro}
            - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT:-"true"}
            - AWS_ENDPOINT=${AWS_ENDPOINT:-http://localhost:9000}
            - AWS_URL=${AWS_URL:-http://localhost:9000/whatspro}

volumes:
    logs_data:
