services:
      laravel:
        build:
            context: .
            dockerfile: Dockerfile.prod
      args:
        WWWGROUP: "${WWWGROUP:-1000}"
    image: whatspro-api:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8090}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER:-1000}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - "./:/var/www/html"
      - "laravel-storage:/var/www/html/storage"
      - "laravel-vendor:/var/www/html/vendor"
    networks:
      - sail
    depends_on:
      - pgsql
      - redis
      - soketi
      - meilisearch
      - rabbitmq
      - mailpit
    healthcheck:
      test: ["CMD", "php", "artisan", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
  pgsql:
    image: "postgres:17"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "sail-pgsql:/var/lib/postgresql/data"
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "${DB_DATABASE}"
        - "-U"
        - "${DB_USERNAME}"
      retries: 3
      timeout: 5s
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "sail-redis:/data"
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  soketi:
    image: "quay.io/soketi/soketi:latest-16-alpine"
    environment:
      SOKETI_DEBUG: "${SOKETI_DEBUG:-0}"
      SOKETI_METRICS_SERVER_PORT: "9601"
      SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID}"
      SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY}"
      SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET}"
    ports:
      - "${PUSHER_PORT:-6001}:6001"
      - "${PUSHER_METRICS_PORT:-9601}:9601"
    networks:
      - sail
  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    environment:
      MEILI_NO_ANALYTICS: "${MEILISEARCH_NO_ANALYTICS:-true}"
      MEILI_MASTER_KEY: "${MEILISEARCH_MASTER_KEY}"
      MEILI_ENV: "production"
      MEILI_API_KEY: "${MEILISEARCH_MASTER_KEY}"
    volumes:
      - "sail-meilisearch:/meili_data"
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - wget
        - "--no-verbose"
        - "--spider"
        - "http://127.0.0.1:7700/health"
      retries: 3
      timeout: 5s
  rabbitmq:
    image: "rabbitmq:4-management"
    hostname: rabbitmq
    ports:
      - "${FORWARD_RABBITMQ_PORT:-5672}:5672"
      - "${FORWARD_RABBITMQ_DASHBOARD_PORT:-15672}:15672"
    environment:
      RABBITMQ_HOST: "%"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
      RABBITMQ_VHOST: "${RABBITMQ_VHOST}"
      RABBITMQ_QUEUE: "${RABBITMQ_QUEUE}"
    volumes:
      - "sail-rabbitmq:/var/lib/rabbitmq"
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - "-q"
        - ping
      retries: 3
      timeout: 5s
  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1026}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8026}:8025"
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-pgsql:
    driver: local
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
  sail-rabbitmq:
    driver: local
  laravel-storage:
    driver: local
  laravel-vendor:
    driver: local
